Add `._with_any_of_*` scope
freeletics/array_enum pull request #12
Opened 2021-10-25 11:26 UTC by csutter

- Adds a scope to retrieve records that have _any_ of the values passed
  in set against them, using Postgres's `&&` operator.
- Refactor duplicated value conversion logic into a lambda

2022-01-04 09:28 UTC, wesleyeewong commented
Extensive tests! 👍 

Can you rebase and add it to the existing map implemented here? https://github.com/freeletics/array_enum/pull/11

2022-01-04 14:16 UTC, wesleyeewong requested changes
Extensive tests! 👍

Can you rebase and add it to the existing map implemented here? #11

2022-01-05 12:04 UTC, csutter commented
Thanks! All done, and added some more info about the new scopes to the README as well 😄

2022-01-05 12:43 UTC, wesleyeewong approved these changes

2022-01-05 12:44 UTC, merged